### ISSUE TITLE
Accent filter not working

### ISSUE THREAD

**Issue by angioedema** [randlet/django-listable#12]
Hi Randy,

I used this for a project and my users are french so they use accent. Unfortunately, filter do not work because of it : 

![image](https://user-images.githubusercontent.com/5978959/129543100-147abf4c-ff5d-4084-8b58-481229622d88.png)

This seems to be an issue of the filter part, but I am not sure. For your information, the database is in Postgres. Do you have any track of why ? I could try to correct the part involved (if this is the case)

BR
Maëva

**Comment by randlet** [comment]
Thank you for the report!  Please try the current master branch which should have a fix (from 545b460b2)

**Comment by angioedema** [comment]
I have tried it, and it works !!!! Thank you !
