### ISSUE TITLE
an enhancement for internationalization

### ISSUE THREAD

**Issue by wangwendong-code** [randlet/django-listable#14]
https://github.com/randlet/django-listable/blob/545b460b22238bcbabbb11e9b5b9255f3df696ca/listable/static/listable/js/listable.js#L31
In dataTable options， I suggest adding "olanguage"  configuration to better adapt to internationalization due to setting LISTABLE_LANGUAGE in settings.py has been provided

**Comment by randlet** [comment]
Thanks for the suggestion. I agree this is a sensible addtion.
