### ISSUE TITLE
ugettext error

### ISSUE THREAD

**Issue by mg64ve** [randlet/django-listable#16]
Just installed this app that looks very nice and I am getting:

`django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'listable.templatetags.listable': cannot import name 'ugettext' from 'django.utils.translation' (/usr/local/lib/python3.9/site-packages/django/utils/translation/__init__.py)`

Any idea if any requirement is missing?

**Comment by randlet** [comment]
I think uggettext was removed in Django 3 or 4 which I haven't test Django listable with yet.
